apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-go-api
  template:
    metadata:
      labels:
        app: simple-go-api
    spec:
      containers:
      - image: tonisanta/simple-go-api
        name: simple-go-api
        ports:
        - containerPort: 8080
        env:
        - name: message
          value: "Hello from base layer"